// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0NzsyvKAYD-mp1qmO9qWxYc3_WyJwmXk',
    appId: '1:704357971793:web:851437cc3530f128838570',
    messagingSenderId: '704357971793',
    projectId: 'suggestion-app-e5128',
    authDomain: 'suggestion-app-e5128.firebaseapp.com',
    storageBucket: 'suggestion-app-e5128.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEWqv2Vop4rcvx_-_nFJ_pDrJDUEuyoV8',
    appId: '1:704357971793:android:9635d3a0d87ba553838570',
    messagingSenderId: '704357971793',
    projectId: 'suggestion-app-e5128',
    storageBucket: 'suggestion-app-e5128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQC4WCLNgwvOKngsZ6D8kD_CwJ-Y36yQs',
    appId: '1:704357971793:ios:6c95081fd70c0a50838570',
    messagingSenderId: '704357971793',
    projectId: 'suggestion-app-e5128',
    storageBucket: 'suggestion-app-e5128.firebasestorage.app',
    iosBundleId: 'com.thales.loginScreenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQC4WCLNgwvOKngsZ6D8kD_CwJ-Y36yQs',
    appId: '1:704357971793:ios:6c95081fd70c0a50838570',
    messagingSenderId: '704357971793',
    projectId: 'suggestion-app-e5128',
    storageBucket: 'suggestion-app-e5128.firebasestorage.app',
    iosBundleId: 'com.thales.loginScreenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0NzsyvKAYD-mp1qmO9qWxYc3_WyJwmXk',
    appId: '1:704357971793:web:857bd7b3688f8c0c838570',
    messagingSenderId: '704357971793',
    projectId: 'suggestion-app-e5128',
    authDomain: 'suggestion-app-e5128.firebaseapp.com',
    storageBucket: 'suggestion-app-e5128.firebasestorage.app',
  );
}
